name: Deploy Frontend and Backend

on:
  push:
    branches:
      - main  # Spustí sa pri pushnutí na vetvu main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout code from GitHub
      - name: Checkout code
        uses: actions/checkout@v2

      # === FRONTEND SETUP ===
      # Set up Node.js environment for frontend
      - name: Set up Node.js for frontend
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      # Install dependencies for frontend
      - name: Install dependencies for frontend
        run: npm install
        working-directory: ./energy-app 

      # Build React app
      - name: Build React app
        run: npm run build
        working-directory: ./energy-app

      # === DEPLOY FRONTEND ===
      # Deploy the frontend build folder to FTP server
      - name: Deploy frontend to FTP
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./energy-app/build/
          server-dir: /solvingenergy.online/
          protocol: ftps  # Skúsime použiť 'ftps' pre bezpečné FTP

      # === BACKEND SETUP ===
      # Set up Node.js environment for backend
      - name: Set up Node.js for backend
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      # Install dependencies for backend
      - name: Install dependencies for backend
        run: npm install
        working-directory: ./backend

      # === DEPLOY BACKEND ===
      # Deploy backend files to FTP server
      - name: Deploy backend to FTP
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./backend/
          server-dir: /api/
          protocol: ftps  # Používame 'ftps'
