name: Deploy Frontend and Backend using Temporary SSH Access

on:
  workflow_dispatch:  # Tento workflow spustíš manuálne, keď budeš pripravený nasadiť.

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout code from GitHub
      - name: Checkout code
        uses: actions/checkout@v2

      # === FRONTEND SETUP ===
      # Set up Node.js environment for frontend
      - name: Set up Node.js for frontend
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      # Install dependencies for frontend
      - name: Install dependencies for frontend
        run: npm install
        working-directory: ./energy-app 

      # Build React app
      - name: Build React app
        run: npm run build
        working-directory: ./energy-app

      # === DEPLOY FRONTEND TO SFTP ===
      # Deploy the frontend build folder to SFTP server using SSH credentials
      - name: Deploy frontend to SSH server
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}  # Tu zadaj aktuálnu hodnotu
          SSH_PORT: ${{ secrets.SSH_PORT }}  # Tu zadaj aktuálnu hodnotu
          SSH_USERNAME: ${{ secrets.SSH_USERNAME }}  # Tu zadaj aktuálnu hodnotu
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}  # Tu zadaj aktuálnu hodnotu (heslo)
          SOURCE: "./energy-app/build/"
          TARGET: "/solvingenergy.online/"
          ARGS: "-rltgoDzv"

      # === BACKEND SETUP ===
      # Set up Node.js environment for backend
      - name: Set up Node.js for backend
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      # Install dependencies for backend
      - name: Install dependencies for backend
        run: npm install
        working-directory: ./backend

      # === DEPLOY BACKEND TO SFTP ===
      # Deploy backend files to SSH server using SSH credentials
      - name: Deploy backend to SSH server
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}  # Tu zadaj aktuálnu hodnotu
          SSH_PORT: ${{ secrets.SSH_PORT }}  # Tu zadaj aktuálnu hodnotu
          SSH_USERNAME: ${{ secrets.SSH_USERNAME }}  # Tu zadaj aktuálnu hodnotu
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}  # Tu zadaj aktuálnu hodnotu (heslo)
          SOURCE: "./backend/"
          TARGET: "/api/"
          ARGS: "-rltgoDzv"
