name: Deploy Frontend and Backend using SSH

on:
  workflow_dispatch:  # Manuálne spustenie workflowu

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout code from GitHub
      - name: Checkout code
        uses: actions/checkout@v2

      # === FRONTEND SETUP ===
      # Set up Node.js environment for frontend
      - name: Set up Node.js for frontend
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      # Install dependencies for frontend
      - name: Install dependencies for frontend
        run: npm install
        working-directory: ./energy-app 

      # Build React app
      - name: Build React app
        run: npm run build
        working-directory: ./energy-app

      # === DEPLOY FRONTEND TO SSH SERVER ===
      - name: Deploy frontend to SSH server
        uses: easingthemes/ssh-deploy@v2.1.5
        with:
          remote_host: ${{ secrets.SSH_HOST }}  # IP alebo doména servera
          remote_user: ${{ secrets.SSH_USER }}  # Používateľské meno
          ssh_private_key: ${{ secrets.SFTP_PRIVATE_KEY }}  # SSH kľúč
          source: "./energy-app/build/"
          target: "/solvingenergy.online/"
          args: "-rltgoDzv"  # Voliteľné rsync parametre

      # === BACKEND SETUP ===
      # Set up Node.js environment for backend
      - name: Set up Node.js for backend
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      # Install dependencies for backend
      - name: Install dependencies for backend
        run: npm install
        working-directory: ./backend

      # === DEPLOY BACKEND TO SSH SERVER ===
      - name: Deploy backend to SSH server
        uses: easingthemes/ssh-deploy@v2.1.5
        with:
          remote_host: ${{ secrets.SSH_HOST }}  # IP alebo doména servera
          remote_user: ${{ secrets.SSH_USER }}  # Používateľské meno
          ssh_private_key: ${{ secrets.SFTP_PRIVATE_KEY }}  # SSH kľúč
          source: "./backend/"
          target: "/api/"
          args: "-rltgoDzv"  # Voliteľné rsync parametre
