name: Deploy Frontend and Backend to SFTP

on:
  push:
    branches:
      - main  # Spustí sa pri pushnutí na vetvu main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout code from GitHub
      - name: Checkout code
        uses: actions/checkout@v2

      # === FRONTEND SETUP ===
      # Set up Node.js environment for frontend
      - name: Set up Node.js for frontend
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      # Install dependencies for frontend
      - name: Install dependencies for frontend
        run: npm install
        working-directory: ./energy-app 

      # Build React app
      - name: Build React app
        run: npm run build
        working-directory: ./energy-app

      # === DEPLOY FRONTEND TO SFTP ===
      # Deploy the frontend build folder to SFTP server using password
      - name: Deploy frontend to SFTP
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SFTP_PRIVATE_KEY }}  # Ak nepoužívaš SSH kľúč, môžeš odstrániť tento riadok
          REMOTE_HOST: ${{ secrets.FTP_SERVER }}
          REMOTE_USER: ${{ secrets.FTP_USERNAME }}
          PASSWORD: ${{ secrets.FTP_PASSWORD }}
          SOURCE: "./energy-app/build/"
          TARGET: "/solvingenergy.online/"
          ARGS: "-rltgoDzv"  # Parametre pre prenos cez rsync

      # === BACKEND SETUP ===
      # Set up Node.js environment for backend
      - name: Set up Node.js for backend
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      # Install dependencies for backend
      - name: Install dependencies for backend
        run: npm install
        working-directory: ./backend

      # === DEPLOY BACKEND TO SFTP ===
      # Deploy backend files to SFTP server using password
      - name: Deploy backend to SFTP
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SFTP_PRIVATE_KEY }}  # Ak nepoužívaš SSH kľúč, môžeš odstrániť tento riadok
          REMOTE_HOST: ${{ secrets.FTP_SERVER }}
          REMOTE_USER: ${{ secrets.FTP_USERNAME }}
          PASSWORD: ${{ secrets.FTP_PASSWORD }}
          SOURCE: "./backend/"
          TARGET: "/api/"
          ARGS: "-rltgoDzv"  # Parametre pre prenos cez rsync
